version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"  # Frontend
      - "8000:8000"  # Backend API
      - "2368:2368"  # Ghost
    environment:
      - NODE_ENV=development
      - VITE_GHOST_CONTENT_API_KEY=${VITE_GHOST_CONTENT_API_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    volumes:
      - ghost-content:/var/lib/ghost/content
      - .env:/app/.env

volumes:
  ghost-content: 