services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - ghost
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: obelisk/vegasguru-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "5173"
    environment:
      - NODE_ENV=production
      - VITE_HOST=vegasseo.guru
      - VITE_PORT=443
      - VITE_PROTOCOL=https
      - VITE_PUBLIC_URL=https://vegasseo.guru
      - VITE_API_URL=https://vegasseo.guru/api
      - VITE_GHOST_URL=https://vegasseo.guru/blog
      - VITE_ASSETS_URL=https://vegasseo.guru/assets
      - VITE_GHOST_CONTENT_API_KEY=${VITE_GHOST_CONTENT_API_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: obelisk/vegasguru-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CORS_ORIGIN=https://vegasseo.guru
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=*
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ghost:
    image: ghost:5-alpine
    user: node
    expose:
      - "2368"
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghostpass
      - database__connection__database=ghost
      - url=https://vegasseo.guru/blog
      - NODE_ENV=production
      - blog__title=Vegas SEO Guru
      - blog__description=Expert SEO Services in Las Vegas
      - admin__url=https://vegasseo.guru/blog/ghost
      - admin__redirects=true
      - admin__session__cookie__secure=true
      - admin__session__cookie__httpOnly=true
      - admin__session__cookie__sameSite=strict
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        sleep 10 &&
        cd /var/lib/ghost &&
        node current/index.js"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2368"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0.32
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ghost-content:
  mysql-data:

networks:
  app-network:
    driver: bridge 