version: '3.8'

services:
  frontend:
    image: obelisk/vegasguru-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_HOST=vegasseo.guru
      - VITE_PORT=443
      - VITE_PROTOCOL=https
      - VITE_PUBLIC_URL=https://vegasseo.guru
      - VITE_GHOST_CONTENT_API_KEY=${VITE_GHOST_CONTENT_API_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: obelisk/vegasguru-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CORS_ORIGIN=https://vegasseo.guru
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ghost:
    image: ghost:5-alpine
    user: node
    ports:
      - "2368:2368"
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghostpass
      - database__connection__database=ghost
      - url=https://vegasseo.guru
      - NODE_ENV=production
      - blog__title=Vegas SEO Guru
      - blog__description=Expert SEO Services in Las Vegas
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        sleep 10 &&
        cd /var/lib/ghost &&
        node current/index.js"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2368"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0.32
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ghost-content:
  mysql-data:

networks:
  app-network:
    driver: bridge 