version: '3.8'

services:
  nginx:
    image: nginx:alpine
    platform: linux/arm64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5173:5173"
    depends_on:
      - frontend
      - backend
      - ghost
    networks:
      - app-network

  frontend:
    image: node:20-slim
    platform: linux/arm64
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y netcat-openbsd && npm install && npm run dev"
    expose:
      - "5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - VITE_GHOST_CONTENT_API_KEY=${VITE_GHOST_CONTENT_API_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: python:3.9-slim
    platform: linux/arm64
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y curl && pip install -r requirements.txt && python -m uvicorn src.services.api_server:app --host 0.0.0.0 --port 8000 --reload"
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ghost:
    image: ghost:5-alpine
    platform: linux/arm64
    expose:
      - "2368"
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghostpass
      - database__connection__database=ghost
      - url=http://localhost:2368
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2368"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0.32
    platform: linux/arm64
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ghost-content:
  mysql-data:

networks:
  app-network:
    driver: bridge