version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"  # Frontend
      - "8000:8000"  # FastAPI
      - "2368:2368"  # Ghost
    environment:
      - NODE_ENV=development
      - VITE_GHOST_CONTENT_API_KEY=${VITE_GHOST_CONTENT_API_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_BRAVE_API_KEY=${VITE_BRAVE_API_KEY}
      - VITE_DEEPSEEK_API_KEY=${VITE_DEEPSEEK_API_KEY}
    volumes:
      - ghost-content:/var/lib/ghost/content
      - .env:/app/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2368"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  ghost-content: 