services:
  vegasguru:
    image: obelisk/vegasguru:latest
    platform: linux/amd64
    user: root
    command: sh -c "apk add --no-cache su-exec && sed -i 's/su ghost -c/su-exec ghost/g' /app/start.sh && sed -i 's/runuser -u ghost --/su-exec ghost /g' /app/start.sh && /app/start.sh"
    ports:
      - "5174:5173"
      - "8001:8000"
      - "2369:2368"
    environment:
      VITE_GHOST_CONTENT_API_KEY: ${VITE_GHOST_CONTENT_API_KEY}
      VITE_OPENAI_API_KEY: ${VITE_OPENAI_API_KEY}
      VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
      VITE_BRAVE_API_KEY: ${VITE_BRAVE_API_KEY}
      VITE_DEEPSEEK_API_KEY: ${VITE_DEEPSEEK_API_KEY}
      NODE_ENV: production
      url: http://localhost:2368
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    volumes:
      - ghost_content:/var/lib/ghost/content
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ghost_content:
    driver: local 