version: '3.8'

services:
  vegasguru:
    image: obelisk/vegasguru:latest
    platform: linux/amd64
    user: root
    command: sh -c "apk add --no-cache su-exec && /app/start.sh"
    ports:
      - "5174:5173"  # Frontend
      - "8001:8000"  # Backend API
      - "2369:2368"  # Ghost
    env_file:
      - .env
    environment:
      NODE_ENV: production
      url: http://0.0.0.0:2368
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    volumes:
      - ghost_content:/var/lib/ghost/content
    restart: unless-stopped

volumes:
  ghost_content:
    driver: local 